version: '3.8'
services:
  db:
    image: postgres
    container_name: sposdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: springintroduction

  app:
    image: spring-demo:latest
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/springintroduction"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "password"
