version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: sposdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    image: spring-demo:latest
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
