apiVersion: v1
kind: Service
metadata:
  name: ""
  namespace: ns-car-springdemo
spec:
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-springapp
  type: NodePort 