#version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: 'posdb'
    restart: always
    ports:
      - 5432:5432
    env_file:
      - path: ./database.env
        required: true