apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ns-car-springdemo
data:
  config.js: |
    window.runtimeConfig = {
      BACKEND_HOST: "http://{{ .Values.backend.host }}"
    };
