apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardemo-springfrontend
  namespace: ns-car-springdemo
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: cardemo-springfrontend
  template:
    metadata:
      labels:
        app: cardemo-springfrontend
    spec:
      containers:
        - name: car-frontend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
      volumes:
        - name: config-volume
          configMap:
            name: frontend-config