apiVersion: v1
kind: Service
metadata:
  name: cardemo-springfrontend
  namespace: ns-car-springdemo
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 35553
      protocol: TCP
      name: http
  selector:
    app: cardemo-springfrontend
  type: NodePort