apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardemo-db-postgresdb
  namespace: ns-car-springdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardemo-db-postgres
  template:
    metadata:
      labels:
        app: cardemo-db-postgres
    spec:
      containers:
        - name: postgresdb
          image: postgres:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cardemo-db-postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cardemo-db-postgres-secret
                  key: password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: cardemo-db-postgres-pvc
