apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cardemo-db-postgres-pvc
  namespace: ns-car-springdemo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
