apiVersion: v1
kind: Secret
metadata:
  name: cardemo-db-postgres-secret
  namespace: ns-car-springdemo
type: Opaque
data:
  username: {{ .Values.postgres.user | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
