apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardemo-springapp
  namespace: ns-car-springdemo
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: cardemo-springapp
  template:
    metadata:
      labels:
        app: cardemo-springapp
    spec:
      containers:
        - name: springapp
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: DATABASE_URL
              value: jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/{{ .Values.database.name }}
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: cardemo-spring-secret
                  key: postgres-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cardemo-spring-secret
                  key: postgres-password
