apiVersion: v1
kind: Secret
metadata:
  name: cardemo-spring-secret
  namespace: ns-car-springdemo
type: Opaque
data:
  postgres-username: {{ .Values.database.username | b64enc }}
  postgres-password: {{ .Values.database.password | b64enc }}
