name: Spring App CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

#    services:
#      postgres:
#        image: postgres:16
#        env:
#          POSTGRES_DB: testdb
#          POSTGRES_USER: testuser
#          POSTGRES_PASSWORD: testpass
#        ports:
#          - 5432:5432
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Run Maven
        run: mvn clean test -Dspring.profiles.active=test
      #        run: mvn clean install -Dspring.datasource.url=jdbc:postgresql://localhost:5432/testdb -Dspring.datasource.username=testuser -Dspring.datasource.password=testpass

      - name: Build and push Docker image
        if: success()
        run: |
          docker build -t myapp:${{ github.sha }} .
