name: "Trivy scan"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Trivy repository scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: '$GITHUB_WORKSPACE/trivy-results.sarif'
          severity: 'MEDIUM,CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: '$GITHUB_WORKSPACE/trivy-results.sarif'